name: Test and PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.19'

    - run: go version


    - name: Install Terratest
      run: |
        go get -u github.com/gruntwork-io/terratest/modules/terraform

    - name: Run Tests
      run: |
        cd /serverless
        make zip && go test -v
