name: Test and PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  assume-role:
    name: Assume Role
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ARN_ROLE }}
        aws-region: us-east-1

    - name: Identity Check
      run: |
        aws sts get-caller-identity

  test:
    runs-on: ubuntu-latest
    needs: assume-role
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.19'

    - run: go version


    - name: Init go mod
      run: |
        go mod init infra-test
        go get -u github.com/gruntwork-io/terratest/modules/terraform

    - name: Run Tests
      run: |
        cd ./serverless
        make zip && go test -v
